/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author fesco
 */
public class Menu extends javax.swing.JFrame {

    public static String usuario;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        JMenu.removeAll();
        DefaultMutableTreeNode menu = new DefaultMutableTreeNode("Menu");
        
        if (usuario.equals("Administrador")) {
            DefaultMutableTreeNode rUsuario = new DefaultMutableTreeNode("00 - Registrar Usuario");
            DefaultMutableTreeNode gUsuario = new DefaultMutableTreeNode("01 - Gestion Usuario");
            DefaultMutableTreeNode cFlujoTarea = new DefaultMutableTreeNode("03 - Crear Flujo de Tareas");
            DefaultMutableTreeNode pDisenador = new DefaultMutableTreeNode("04 - Panel Diseñador");
            menu.add(rUsuario);
            menu.add(gUsuario);
            menu.add(cFlujoTarea);
            menu.add(pDisenador);
            JMenu.setModel(new javax.swing.tree.DefaultTreeModel(menu));
        } else if (usuario.equals("Funcionario")) {
            DefaultMutableTreeNode rCliente = new DefaultMutableTreeNode("05 - Registrar Cliente");
            DefaultMutableTreeNode tareas = new DefaultMutableTreeNode("07 - Tareas");
            DefaultMutableTreeNode panelControl = new DefaultMutableTreeNode("08 - Panel de Control");
            menu.add(rCliente);
            menu.add(tareas);
            menu.add(panelControl);
            JMenu.setModel(new javax.swing.tree.DefaultTreeModel(menu));
        } else {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JMenu = new javax.swing.JTree();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JMenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JMenu);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escritorio)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuMouseClicked
        TreePath tp = JMenu.getPathForLocation(evt.getX(), evt.getY());
        if (tp != null) {
            String[] aux = tp.toString().split(",")[1].split("-");
            String auxFin = aux[0].trim();
            switch (auxFin) {
                case "00":
                    this.escritorio.removeAll();
                    RegistrarUsuariosF opt1 = new RegistrarUsuariosF();
                    this.escritorio.add(opt1);
                    opt1.show();
                    this.escritorio.repaint();
                    break;
                case "01":
                    this.escritorio.removeAll();
                    GestionarUsuariosF opt2 = new GestionarUsuariosF();
                    this.escritorio.add(opt2);
                    opt2.show();
                    this.escritorio.repaint();
                    break;
                case "03":
                    this.escritorio.removeAll();
                    TareasRegistroF opt4 = new TareasRegistroF();
                    this.escritorio.add(opt4);
                    opt4.show();
                    this.escritorio.repaint();
                    break;
                case "04":
                    this.escritorio.removeAll();
                    DisenadorProcesosF opt5 = new DisenadorProcesosF();
                    this.escritorio.add(opt5);
                    opt5.show();
                    this.escritorio.repaint();
                    break;
                case "05":
                    this.escritorio.removeAll();
                    RegistrarClientesF opt6 = new RegistrarClientesF();
                    this.escritorio.add(opt6);
                    opt6.show();
                    this.escritorio.repaint();
                    break;
                case "07":
                    this.escritorio.removeAll();
                    TareasRegistroF opt8 = new TareasRegistroF();
                    this.escritorio.add(opt8);
                    opt8.show();
                    this.escritorio.repaint();
                    break;
                 case "08":
                    this.escritorio.removeAll();
                    PanelControl opt9 = new PanelControl();
                    this.escritorio.add(opt9);
                    opt9.show();
                    this.escritorio.repaint();
                    break;
            }
        }
    }//GEN-LAST:event_JMenuMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JMenu;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
